name: pull_request

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Requirements
        run: make requirements

      - name: Build
        run: make build

      - name: Lint check (ruff)
        run: make check-lint

      - name: Type check (mypy)
        run: make check-type

      - name: Test
        run: make test
